services:
  - type: web
    name: plantnet2anki
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python plantnet2anki_gui.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
